#!/bin/sh
#tv_grab_file for remote XMLTV file

        wget -r -O /home/hts/.xmltv/tv_grab_file.xmltv "$1"
        cat /home/hts/.xmltv/tv_grab_file.xmltv | socat - UNIX-CONNECT:/home/hts/.hts/tvheadend/epggrab/xmltv.sock 2>/dev/null
